# version: '3'
# services:
#     app:
#         restart: always
#         build: .
#         env_file:
#             - .env
#         ports:
#             - "7070:8181"
#         container_name: fundingapp